In [161]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import joblib

In [113]:
carvana = pd.read_csv("carvana.csv")

In [114]:
carvana.head()

              Name   Year  Miles  Price
0   Chevrolet Trax   2018  41946  16990
1      GMC Terrain   2020  45328  23990
2    Jeep Wrangler   2012  81068  21590
3    Jeep Renegade   2019  35372  21590
4            BMW X  20173  68992  22990

In [115]:
carvana.info()

<class 'pandas.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    22000 non-null  str
 1   Year    22000 non-null  int64
 2   Miles   22000 non-null  int64
 3   Price   22000 non-null  int64
dtypes: int64(3), str(1)
memory usage: 988.6 KB

In [116]:
carvana['Year'].unique()

array([    2018,     2020,     2012,     2019,    20173,     2016,
           2017,     2015,     2014,     2010,    20194,    20165,
           2013,    20133,     2011,  2013500,  2017124,     2021,
           2022,   201650,    20163,    20215,    20113,    20152,
       20141500,   202130,    20204,    20153,  2014500,  2016500,
          20103,    20156,  2017500,   201040,  2013300,  2015200,
        2013150,    20125,    20185,    20166,    20146,    20213,
         202180,   201860,    20184,    20203,    20143,    20144,
         201550,   202050,   202150,    20199,    20219,    20205,
         201730,   202060,  2018500,  2015500,  2010370,   201750,
          20174,   201360,   200970,    20193,    20145,    20164,
          20123,    20176,  2016200,   201560,  2015900,    20161,
        2016900,    20154,    20182,    20157,  2019500,    20183,
          20122,    20129,    20114,  2020150, 20211500,    20135,
          20196,  2014200, 20201500,    20195,    20134,    20169,
         201850,  2021300,    20095,  2016300,  2013200,    20105,
         201460,     2009,    20136,    20151,  2020300,    20115,
          20214,   201660,    20209,    20175,   201980,    20172,
        2012300,  2018300,   201450, 20151500,   201540,   201960,
          20202,   202286,    20186,   201760,    20155,    20112,
          20212,    20225,    20232,    20206,    20111, 20171500,
         202140,  2019124,   202260,    20181,   201940,    20222,
        2018150,  2013911,  2021150,    20224, 20161500,    20223,
       20191500,  2016370,   201950,   202230, 20222500, 20223500,
       20181500,  2014370, 20221500,   201570,   201890,   201880,
          20162,  2017718,    20124,  2017150,  2017370,   201790,
         202090,  2022150,   201990,    20226,    20201,   201930,
          20216, 20152500,    20147,   201970,   201886,  2016150,
        2018718,    20191,    20189,  2015300,   201690,   202270,
         202160,    20187,     2023,    20149,   201270,    20211,
        2019150,   202030,    20192,   201780,    20171,  2018124,
        2019300,    20128,    20093,   201830,    20096,   201260,
        2012200,  2012500,  2017200,    20127,    20101,    20126,
         201770,  2017300,    20094,  2011200, 20131500,  2014300,
          20141,    20131,    20104,    20139,    20132,  2011370,
          20142])

In [117]:
# fixing the column year

In [118]:
carvana[carvana['Year']>2026]

                       Name     Year   Miles  Price
4                     BMW X    20173   68992  22990
31      Mitsubishi Mirage G    20194   24065  15990
34                MAZDA CX-    20165   66644  18590
39              MAZDA MAZDA    20133  100316  12990
46                    FIAT   2013500   44087  15990
...                     ...      ...     ...    ...
21952                 BMW X    20151   35706  22990
21963       MAZDA MX- Miata    20165   42003  22590
21970           MAZDA MAZDA    20123   89624  13990
21975                 BMW X    20151   35706  22990
21981             MAZDA CX-    20155   31686  21990

[2851 rows x 4 columns]

In [119]:
carvana['Year'].min()

2009

In [120]:
carvana['Year'].max()

20223500

In [121]:
carvana.describe()

               Year          Miles          Price
count  2.200000e+04   22000.000000   22000.000000
mean   1.946648e+05   54445.697318   20707.285136
std    1.630370e+06   25685.933926    6535.580304
min    2.009000e+03      53.000000   10990.000000
25%    2.014000e+03   35512.000000   16590.000000
50%    2.017000e+03   51890.000000   19590.000000
75%    2.020000e+03   73191.000000   22990.000000
max    2.022350e+07  120167.000000  102990.000000

In [122]:
carvana['Name'].value_counts()

Name
 Toyota Corolla              835
 Hyundai Elantra             738
 Toyota Camry                725
 Nissan Rogue                528
 Honda Accord                521
                            ...
 Chevrolet Suburban            1
 Chevrolet City Express        1
 Volkswagen New Beetle         1
 Chevrolet Malibu Limited      1
Kia Sorento                    1
Name: count, Length: 416, dtype: int64

In [123]:
carvana["Year"] = carvana['Year'].astype(str).str[:4].astype(int)

In [124]:
carvana[carvana['Year'] > 2026]

Empty DataFrame
Columns: [Name, Year, Miles, Price]
Index: []

In [125]:
X = carvana.iloc[:,:-1]

In [126]:
X

                            Name  Year  Miles
0                 Chevrolet Trax  2018  41946
1                    GMC Terrain  2020  45328
2                  Jeep Wrangler  2012  81068
3                  Jeep Renegade  2019  35372
4                          BMW X  2017  68992
...                          ...   ...    ...
21995               Honda Accord  2014  98085
21996              Dodge Charger  2016  62616
21997                Ford Taurus  2013  50345
21998   Toyota Corolla Hatchback  2020  27945
21999                Honda Civic  2012  70676

[22000 rows x 3 columns]

In [127]:
y = carvana['Price']

In [128]:
y

0        16990
1        23990
2        21590
3        21590
4        22990
         ...
21995    17590
21996    23990
21997    16990
21998    23990
21999    14990
Name: Price, Length: 22000, dtype: int64

In [129]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [130]:
print(X_train.shape)
print(y_train.shape)

(17600, 3)
(17600,)

In [131]:
print(X_test.shape)
print(y_test.shape)

(4400, 3)
(4400,)

In [132]:
# data pre-processing

In [133]:
numeric_features = ["Year","Miles"]
categorical_feature = ["Name"]

In [134]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),numeric_features),
        ("cat",OneHotEncoder(handle_unknown="ignore"),categorical_feature)
    ],remainder="drop"
)

In [135]:
pipeline = Pipeline(steps=[
    ("preprocessor",preprocessor),
    ("model",LinearRegression())
])

In [136]:
pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Year', 'Miles']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Name'])])),
                ('model', LinearRegression())])

In [137]:
# training the dataset

In [138]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Year', 'Miles']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Name'])])),
                ('model', LinearRegression())])

In [139]:
y_pred =pipeline.predict(X_test)
y_pred

array([18679.09129681, 13397.39683632, 22693.28868136, ...,
       20392.74300341, 14767.07949929, 18193.00959137], shape=(4400,))

In [142]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

In [146]:
print(mse)
print(rmse)

6230977.260477742
2496.1925527646586

In [148]:
r2 = r2_score(y_test,y_pred)
r2

0.854677514705805

In [151]:
print("Training Accuracy:{:.2f}".format(pipeline.score(X_train,y_train)))
print("Testing Accuracy:{:.2f}".format(pipeline.score(X_test,y_test)))

Training Accuracy:0.88
Testing Accuracy:0.85

In [158]:
user_input = {
    "Name":"Toyota Sienna",
    "Year":2022,
    "Miles": 165000
}
user_input_df = pd.DataFrame([user_input])
user_input_df

            Name  Year   Miles
0  Toyota Sienna  2022  165000

In [160]:
pipeline.predict(user_input_df)

array([23652.85803218])

In [162]:
joblib.dump(pipeline,"carvana_pipeline.pkl")

['carvana_pipeline.pkl']